apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noths-service-std.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noths-service-std.labels" . | nindent 4 }}
    app: {{ template "noths-service-std.name" . }}
    chart: {{ template "noths-service-std.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "noths-service-std.selectorLabels" . | nindent 6 }}
      app: {{ template "noths-service-std.name" . }}
      release: {{ .Release.Name }}
      {{- if .Values.securityGroup.create }}
      role: {{ template "noths-service-std.serviceAccountName" . }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "noths-service-std.selectorLabels" . | nindent 8 }}
        app: {{ template "noths-service-std.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.securityGroup.create }}
        role: {{ template "noths-service-std.serviceAccountName" . }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "noths-service-std.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "noths-service-std.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            {{- $rootPath := . }}
            {{- range $secretName, $values := .Values.deployment.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "noths-service-std.name" $rootPath }}-{{ $secretName | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        name: {{ .Release.Namespace }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
