{{- if .Values.appMesh.gateway.private.route.create -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: {{ .Values.appMesh.gateway.private.route.name }}
  namespace: {{ .Values.appMesh.gateway.private.route.namespace }}
  labels:
    gateway: {{ .Values.appMesh.gateway.private.route.gatewayName }}
spec:
  httpRoute:
    match:
      prefix: {{ .Values.appMesh.gateway.private.route.prefix }}
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: {{ template "noths-service-std.name" . }}
            namespace: {{ .Release.Namespace }}
{{- end -}}
