apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: {{ template "noths-service-std.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "noths-service-std.name" . }}
    chart: {{ template "noths-service-std.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  awsName: {{ template "noths-service-std.name" . }}.{{ .Values.deployment.dnsDomain }}
  provider:
    virtualNode:
      virtualNodeRef:
        name: {{ template "noths-service-std.name" . }}
