apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-example.fullname" . }}
  labels:
    {{- include "backend-example.labels" . | nindent 4 }}
    App: {{ template "backend-example.name" . }}
    chart: {{ template "backend-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end }}
      {{- if .Values.service.portName }}
      name: {{ .Values.service.portName }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "backend-example.selectorLabels" . | nindent 4 }}
    {{- with required "Valid 'selectors' for the Service are required" .Values.service.selectorLabels }}
    {{ toYaml .  }}
    {{- end }}
