apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: {{ template "backend-example.fullname" . }}-blue
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-example.labels" . | nindent 4 }}
    app: {{ template "backend-example.name" . }}-blue
    chart: {{ template "backend-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: blue
spec:
  podSelector:
    matchLabels:
      app: {{ template "backend-example.name" . }}
      release: {{ .Release.Name }}
      version: blue
  listeners:
  - portMapping:
      port: {{ .Values.deployment.containerPort }}
      protocol: http  
    {{- if .Values.appMesh.backendVirtualServices }}
    {{ toYaml .Values.appMesh.healthCheck }}
    {{- end }}
  backends:
    - virtualService:
        virtualServiceRef:
          name: {{ template "backend-example.fullname" . }}
  serviceDiscovery:
    awsCloudMap:
      namespaceName: {{ .Values.deployment.dnsDomain | quote }}
      serviceName: {{ template "backend-example.fullname" . }}-blue
