{{- if .Values.appMesh.gateway.create -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: {{ .Values.appMesh.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchLabels:
      gateway: {{ .Values.appMesh.gateway.name }}
  podSelector:
    matchLabels:
      app: {{ .Values.appMesh.gateway.name }}
  listeners:
    - portMapping:
        port: {{ .Values.appMesh.gateway.port }}
        protocol: http
{{- end -}}
