# Default values for appmesh-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1

# aws config
aws:
  region: eu-west-1

image:
  repository: "" #repo with image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tagBlue: "" # e.g latest
  tagGreen: "" # e.g latest

appMesh:
  create: true
  external: false
  name: # e.g test-mesh
  egressFilterType: "DROP_ALL"
  aws:
    arn: # The ARN of an existing mesh set external to true above
    accountID: # If external provide an external accountID

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: false
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

securityGroup:
  create: false
  name: "" #appmesh-core
  groupIds: [] # A list of security group ids to map to
    # - <sg-abc123>


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# podDisruptionBudget -- Pod disruption budget.
podDisruptionBudget:
  maxUnavailable: 1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Priorities Expander
expanderPriorities: {}

extraArgs:
  logtostderr: true
  stderrthreshold: info
