{{- if .Values.appMesh.gateway.route.create -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: {{ .Values.appMesh.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  httpRoute:
    match:
      prefix: {{ .Values.appMesh.gateway.route.prefix }}
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: {{ template "noths-service-ha.name" . }}
{{- end -}}
