# Default values for noths-service-std.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1

# aws config
aws:
  region: eu-west-1

image:
  repository: "" #repo with image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "" # e.g latest

deployment:
  containerPort: 8080
  dnsDomain: "" # e.g svc.cluster.local
  env: # Environmet variables please provide as a key / value map
  secrets: {}  # Secret Variables (pumped to kube secrets) Please provides as a key / value map
  enableProbes: false
  livenessProbe: {}
  readinessProbe: {}

appMesh:
  create: false
  external: false
  name: # e.g test-mesh
  targets:  # Uncomment snippet below to set route(s) to your existing back-end app Virtual Node
    - vNodeName: ""
      weight: 100
  gateway:
    api:
      route:
        name: # The name of the appmesh api gateway
        namespace: ""
        create: false
        port: 8088
        prefix: "/"
    www:
      route:
        name: # The name of the appmesh www gateway
        namespace: ""
        create: true
        port: 8088
        prefix: "/"
    private:
      route:
        name: # The name of the appmesh private gateway
        namespace: ""
        create: false
        port: 8088
        prefix: "/"
  router:
    listenerProtocol: http
  node:
    enableHealthCheck: false
    healthCheck:
      healthyThreshold: 2
      intervalMillis: 5000
      path: /health 
      protocol: http
      timeoutMillis: 2000
      unhealthyThreshold: 2
  envoy:
    image: "public.ecr.aws/appmesh/aws-appmesh-envoy:v1.19.0.0-prod"
  aws:
    arn: # The ARN of an existing mesh set external to true above
    accountID: # If external provide an external accountID

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: true
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

securityGroup:
  create: false
  name: "" #noths-service-std
  groupIds: [] # A list of security group ids to map to
    # - <sg-abc123>

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# podDisruptionBudget -- Pod disruption budget.
podDisruptionBudget:
  maxUnavailable: 1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  portName: http
  targetPort: http

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## Priorities Expander
expanderPriorities: {}

extraArgs:
  logtostderr: true
  stderrthreshold: info
