{{- range $secretName, $values := .Values.deployment.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "noths-service-std.fullname" $ }}-{{ $secretName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "noths-service-std.labels" $ | nindent 4 }}
    app: {{ template "noths-service-std.fullname" $ }}
    chart: {{ template "noths-service-std.chart" $ }}
    release: {{ $.Release.Name }}
type: {{ $.Values.deployment.secret_type }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{$value | b64enc }}
  {{- end }}
---
{{- end }}
