apiVersion: v1
kind: Service
metadata:
  name: {{ include "noths-service-ha.fullname" . }}-green
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noths-service-ha.labels" . | nindent 4 }}
    app: {{ template "noths-service-ha.name" . }}
    chart: {{ template "noths-service-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: green
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end }}
      {{- if .Values.service.portName }}
      name: {{ .Values.service.portName }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "noths-service-ha.selectorLabels" . | nindent 4 }}
    app: {{ include "noths-service-ha.fullname" . }}
    version: green
