# Default values for backend-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCountBlue: 1
replicaCountGreen: 1

# aws config
aws:
  region: eu-west-1

image:
  repository: "" #repo with image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tagBlue: "" # e.g latest
  tagGreen: "" # e.g latest

deployment:
  containerPort: 8080
  dnsDomain: "" # e.g svc.cluster.local

backend:
  envAddresses: # These entries will be turned into environment variables e.g: 
    # Settings_ServiceBaseUrl: http://green.backend.svc.cluster.local/
    ServiceName: ""

appMesh:
  name: # e.g test-mesh
  enableExternalTraffic: false
  vRouterListenerProtocol: http
  gatewayRouteMatchPrefix: # Supply override here, otherwise it's "/service-name"
  targets:  # Uncomment snippet below to set route(s) to your existing back-end app Virtual Node
    - vNodeName: ""
      weight: 100
  gateway:
    route:
      create: true
      name: # The name of the appmesh gateway
      port: 8088
      lbType: nlb
      prefix: "/"
  envoy:
    image: "public.ecr.aws/appmesh/aws-appmesh-envoy:v1.19.0.0-prod"

  healthCheck:
    healthyThreshold: 2
    intervalMillis: 5000
    path: /health 
    protocol: http
    timeoutMillis: 2000
    unhealthyThreshold: 2

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: true
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

securityGroup:
  create: false
  name: "" #backend-example
  groupIds: [] # A list of security group ids to map to
    # - <sg-abc123>

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# podDisruptionBudget -- Pod disruption budget.
podDisruptionBudget:
  maxUnavailable: 1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  portName: http
  targetPort: http

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

## Priorities Expander
expanderPriorities: {}

extraArgs:
  logtostderr: true
  stderrthreshold: info
