{{- if .Values.appMesh.gateway.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appMesh.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appMesh.gateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appMesh.gateway.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appmesh-core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.appMesh.envoy.image }}
          ports:
            - containerPort: {{ .Values.appMesh.gateway.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        name: {{ .Release.Namespace }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
