{{- if .Values.appMesh.gateway.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appMesh.gateway.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.appMesh.gateway.lbType }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appMesh.gateway.port }}
      name: {{ .Values.appMesh.gateway.proto }}
  selector:
    app: {{ .Values.appMesh.gateway.name }}
{{- end -}}
