{{- if .Values.appMesh.enableExternalTraffic -}}
{{- $fullName := include "appmesh-core.fullname" . -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "appmesh-core.labels" . | nindent 4 }}
    app: {{ template "appmesh-core.name" . }}
    chart: {{ template "appmesh-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  httpRoute:
    match:
      prefix: {{ .Values.appMesh.gatewayRouteMatchPrefix | default (printf "/%s" $fullName) }}
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: {{ $fullName }}
{{- end -}}
