apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-deploy.fullname" . }}-blue
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-deploy.labels" . | nindent 4 }}
    app: {{ template "eks-deploy.name" . }}
    chart: {{ template "eks-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: blue
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCountBlue }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eks-deploy.selectorLabels" . | nindent 6 }}
      app: {{ template "eks-deploy.name" . }}
      release: {{ .Release.Name }}
      version: blue
      {{- if .Values.securityGroup.create }}
      role: {{ template "eks-deploy.serviceAccountName" . }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eks-deploy.selectorLabels" . | nindent 8 }}
        app: {{ template "eks-deploy.name" . }}
        release: {{ .Release.Name }}
        version: blue
        {{- if .Values.securityGroup.create }}
        role: {{ template "eks-deploy.serviceAccountName" . }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eks-deploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagBlue | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        name: {{ .Release.Namespace }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
