{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "eks-deploy.labels" . | indent 4 }}
  name: {{ template "eks-deploy.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
{{- if eq (default "" .Values.extraArgs.expander) "priority" }}
      - list
      - watch
{{- end }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - eks-deploy-status
{{- if eq (default "" .Values.extraArgs.expander) "priority" }}
      - eks-deploy-priority-expander
{{- end }}
    verbs:
      - delete
      - get
      - update
{{- if eq (default "" .Values.extraArgs.expander) "priority" }}
      - watch
{{- end }}
{{- end -}}
