{{- if .Values.appMesh.gateway.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appMesh.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "appmesh-gateway.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.appMesh.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.appMesh.service.type }}
  externalTrafficPolicy: {{ .Values.appMesh.service.externalTrafficPolicy }}
  ports:
    {{- range $port := .Values.appMesh.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $.Values.appMesh.gateway.port }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    app: {{ .Values.appMesh.gateway.name }}
{{- end -}}
