{{- if .Values.appMesh.gateway.create -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: {{ .Values.appMesh.gateway.name }}
spec:
  awsName: {{ .Values.appMesh.gateway.name }}
  {{- if .Values.appMesh.gateway.matchAllNamespaces }}
  namespaceSelector: {}
  {{- else }}
  namespaceSelector:
    matchLabels:
      gateway: {{ .Values.appMesh.gateway.name }}
  {{- end }}
  podSelector:
    matchLabels:
      app: {{ .Values.appMesh.gateway.name }}
  listeners:
    - portMapping:
        port: {{ .Values.appMesh.gateway.port }}
        protocol: {{ .Values.appMesh.gateway.proto }}
  logging:
    accessLog:
      file:
        path: {{ .Values.appMesh.gateway.logging.file }}
{{- end -}}
